CREATE TYPE "UserRole" AS ENUM ('EXPORTER','IMPORTER');
CREATE TYPE "VerificationStatus" AS ENUM ('PENDING','VERIFIED','MANUAL_REVIEW','REJECTED');
CREATE TYPE "RequestStatus" AS ENUM ('DRAFT','SUBMITTED','UNDER_REVIEW','CHANGES_REQUESTED','ACCEPTED','REJECTED','NEGOTIATING','AGREEMENT_REACHED','COMPLETED','CANCELLED');
CREATE TYPE "RequirementFieldType" AS ENUM ('TEXT','TEXTAREA','NUMBER','DATE','SELECT','BOOLEAN','FILE');
CREATE TYPE "DocumentReviewStatus" AS ENUM ('PENDING','APPROVED','WARNING','MANUAL_REVIEW');
CREATE TYPE "AgreementStatus" AS ENUM ('DRAFT','CONFIRMED','COMPLETED');
CREATE TYPE "OfferStatus" AS ENUM ('ACTIVE','INACTIVE','CLOSED');

CREATE TABLE "User" ("id" UUID PRIMARY KEY, "email" TEXT NOT NULL UNIQUE, "passwordHash" TEXT NOT NULL, "role" "UserRole" NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Company" ("id" UUID PRIMARY KEY, "ownerUserId" UUID NOT NULL UNIQUE, "legalName" TEXT NOT NULL, "tradeName" TEXT, "countryCode" TEXT NOT NULL, "taxId" TEXT NOT NULL, "website" TEXT, "phone" TEXT, "contactEmail" TEXT NOT NULL, "description" TEXT, "logoUrl" TEXT, "verificationStatus" "VerificationStatus" NOT NULL DEFAULT 'PENDING', "verifiedAt" TIMESTAMP(3), "verificationSource" TEXT, "verificationNotes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Company_countryCode_taxId_key" UNIQUE("countryCode","taxId"));
CREATE TABLE "CompanyVerification" ("id" UUID PRIMARY KEY, "companyId" UUID NOT NULL, "type" TEXT NOT NULL, "status" "VerificationStatus" NOT NULL, "source" TEXT NOT NULL, "result" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "BuyingInterest" ("id" UUID PRIMARY KEY, "importerCompanyId" UUID NOT NULL, "productName" TEXT NOT NULL, "category" TEXT, "description" TEXT, "minQuantityTons" DOUBLE PRECISION NOT NULL, "maxQuantityTons" DOUBLE PRECISION, "minTargetPrice" DOUBLE PRECISION, "maxTargetPrice" DOUBLE PRECISION, "currency" TEXT NOT NULL, "preferredOriginCountries" TEXT[], "requiredCertifications" TEXT[], "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "RequirementForm" ("id" UUID PRIMARY KEY, "importerCompanyId" UUID NOT NULL, "buyingInterestId" UUID, "title" TEXT NOT NULL, "description" TEXT, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "RequirementField" ("id" UUID PRIMARY KEY, "formId" UUID NOT NULL, "label" TEXT NOT NULL, "type" "RequirementFieldType" NOT NULL, "required" BOOLEAN NOT NULL DEFAULT false, "helpText" TEXT, "options" JSONB, "order" INTEGER NOT NULL DEFAULT 0);
CREATE TABLE "DocumentRequirement" ("id" UUID PRIMARY KEY, "formId" UUID NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "required" BOOLEAN NOT NULL DEFAULT true, "instructionsForAI" TEXT, "templateUrl" TEXT, "order" INTEGER NOT NULL DEFAULT 0);
CREATE TABLE "ExportOffer" ("id" UUID PRIMARY KEY, "exporterCompanyId" UUID NOT NULL, "productName" TEXT NOT NULL, "category" TEXT, "description" TEXT, "quantityTons" DOUBLE PRECISION NOT NULL, "pricePerKg" DOUBLE PRECISION NOT NULL, "currency" TEXT NOT NULL, "certifications" TEXT[], "preferredRegion" TEXT, "preferredCountries" TEXT[], "availabilityDate" TIMESTAMP(3), "status" "OfferStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "ExportRequest" ("id" UUID PRIMARY KEY, "offerId" UUID NOT NULL, "importerCompanyId" UUID NOT NULL, "buyingInterestId" UUID, "requirementFormId" UUID, "status" "RequestStatus" NOT NULL DEFAULT 'DRAFT', "matchScoreSnapshot" INTEGER, "matchFeedbackSnapshot" JSONB, "submittedAt" TIMESTAMP(3), "acceptedAt" TIMESTAMP(3), "rejectedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "RequestStatusHistory" ("id" UUID PRIMARY KEY, "requestId" UUID NOT NULL, "fromStatus" "RequestStatus", "toStatus" "RequestStatus" NOT NULL, "actorUserId" UUID NOT NULL, "note" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "RequestFieldResponse" ("id" UUID PRIMARY KEY, "requestId" UUID NOT NULL, "fieldId" UUID NOT NULL, "value" JSONB NOT NULL, CONSTRAINT "RequestFieldResponse_requestId_fieldId_key" UNIQUE("requestId","fieldId"));
CREATE TABLE "DocumentSubmission" ("id" UUID PRIMARY KEY, "requestId" UUID NOT NULL, "documentRequirementId" UUID, "uploaderCompanyId" UUID NOT NULL, "fileName" TEXT NOT NULL, "storagePath" TEXT NOT NULL, "mimeType" TEXT NOT NULL, "fileSize" INTEGER NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "DocumentAnalysis" ("id" UUID PRIMARY KEY, "submissionId" UUID NOT NULL UNIQUE, "provider" TEXT NOT NULL, "documentType" TEXT NOT NULL, "status" "DocumentReviewStatus" NOT NULL, "confidence" DOUBLE PRECISION NOT NULL, "summary" TEXT NOT NULL, "issues" JSONB NOT NULL, "recommendations" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Agreement" ("id" UUID PRIMARY KEY, "requestId" UUID NOT NULL UNIQUE, "agreementCode" TEXT NOT NULL UNIQUE, "finalQuantityTons" DOUBLE PRECISION NOT NULL, "pricePerKg" DOUBLE PRECISION NOT NULL, "currency" TEXT NOT NULL, "incoterm" TEXT NOT NULL, "destination" TEXT NOT NULL, "estimatedDelivery" TIMESTAMP(3), "notes" TEXT, "estimatedTradeValue" DOUBLE PRECISION NOT NULL, "status" "AgreementStatus" NOT NULL DEFAULT 'CONFIRMED', "agreementPdfPath" TEXT, "completionPdfPath" TEXT, "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);

ALTER TABLE "Company" ADD CONSTRAINT "Company_ownerUserId_fkey" FOREIGN KEY("ownerUserId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "CompanyVerification" ADD CONSTRAINT "CompanyVerification_companyId_fkey" FOREIGN KEY("companyId") REFERENCES "Company"("id") ON DELETE CASCADE;
ALTER TABLE "BuyingInterest" ADD CONSTRAINT "BuyingInterest_importerCompanyId_fkey" FOREIGN KEY("importerCompanyId") REFERENCES "Company"("id") ON DELETE CASCADE;
ALTER TABLE "RequirementForm" ADD CONSTRAINT "RequirementForm_importerCompanyId_fkey" FOREIGN KEY("importerCompanyId") REFERENCES "Company"("id") ON DELETE CASCADE;
ALTER TABLE "RequirementForm" ADD CONSTRAINT "RequirementForm_buyingInterestId_fkey" FOREIGN KEY("buyingInterestId") REFERENCES "BuyingInterest"("id") ON DELETE SET NULL;
ALTER TABLE "RequirementField" ADD CONSTRAINT "RequirementField_formId_fkey" FOREIGN KEY("formId") REFERENCES "RequirementForm"("id") ON DELETE CASCADE;
ALTER TABLE "DocumentRequirement" ADD CONSTRAINT "DocumentRequirement_formId_fkey" FOREIGN KEY("formId") REFERENCES "RequirementForm"("id") ON DELETE CASCADE;
ALTER TABLE "ExportOffer" ADD CONSTRAINT "ExportOffer_exporterCompanyId_fkey" FOREIGN KEY("exporterCompanyId") REFERENCES "Company"("id") ON DELETE CASCADE;
ALTER TABLE "ExportRequest" ADD CONSTRAINT "ExportRequest_offerId_fkey" FOREIGN KEY("offerId") REFERENCES "ExportOffer"("id") ON DELETE RESTRICT;
ALTER TABLE "ExportRequest" ADD CONSTRAINT "ExportRequest_importerCompanyId_fkey" FOREIGN KEY("importerCompanyId") REFERENCES "Company"("id") ON DELETE RESTRICT;
ALTER TABLE "ExportRequest" ADD CONSTRAINT "ExportRequest_buyingInterestId_fkey" FOREIGN KEY("buyingInterestId") REFERENCES "BuyingInterest"("id") ON DELETE SET NULL;
ALTER TABLE "ExportRequest" ADD CONSTRAINT "ExportRequest_requirementFormId_fkey" FOREIGN KEY("requirementFormId") REFERENCES "RequirementForm"("id") ON DELETE SET NULL;
ALTER TABLE "RequestStatusHistory" ADD CONSTRAINT "RequestStatusHistory_requestId_fkey" FOREIGN KEY("requestId") REFERENCES "ExportRequest"("id") ON DELETE CASCADE;
ALTER TABLE "RequestStatusHistory" ADD CONSTRAINT "RequestStatusHistory_actorUserId_fkey" FOREIGN KEY("actorUserId") REFERENCES "User"("id") ON DELETE RESTRICT;
ALTER TABLE "RequestFieldResponse" ADD CONSTRAINT "RequestFieldResponse_requestId_fkey" FOREIGN KEY("requestId") REFERENCES "ExportRequest"("id") ON DELETE CASCADE;
ALTER TABLE "RequestFieldResponse" ADD CONSTRAINT "RequestFieldResponse_fieldId_fkey" FOREIGN KEY("fieldId") REFERENCES "RequirementField"("id") ON DELETE CASCADE;
ALTER TABLE "DocumentSubmission" ADD CONSTRAINT "DocumentSubmission_requestId_fkey" FOREIGN KEY("requestId") REFERENCES "ExportRequest"("id") ON DELETE CASCADE;
ALTER TABLE "DocumentSubmission" ADD CONSTRAINT "DocumentSubmission_documentRequirementId_fkey" FOREIGN KEY("documentRequirementId") REFERENCES "DocumentRequirement"("id") ON DELETE SET NULL;
ALTER TABLE "DocumentSubmission" ADD CONSTRAINT "DocumentSubmission_uploaderCompanyId_fkey" FOREIGN KEY("uploaderCompanyId") REFERENCES "Company"("id") ON DELETE RESTRICT;
ALTER TABLE "DocumentAnalysis" ADD CONSTRAINT "DocumentAnalysis_submissionId_fkey" FOREIGN KEY("submissionId") REFERENCES "DocumentSubmission"("id") ON DELETE CASCADE;
ALTER TABLE "Agreement" ADD CONSTRAINT "Agreement_requestId_fkey" FOREIGN KEY("requestId") REFERENCES "ExportRequest"("id") ON DELETE RESTRICT;

CREATE INDEX "Company_verificationStatus_idx" ON "Company"("verificationStatus");
CREATE INDEX "BuyingInterest_productName_active_idx" ON "BuyingInterest"("productName","active");
CREATE INDEX "ExportOffer_productName_status_idx" ON "ExportOffer"("productName","status");
CREATE INDEX "ExportRequest_importerCompanyId_status_idx" ON "ExportRequest"("importerCompanyId","status");
CREATE INDEX "ExportRequest_offerId_idx" ON "ExportRequest"("offerId");
